services:
  mongo:
    image: mongo:4
    container_name: mongo_secure_privacy
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=secure-privacy
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Test123!
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  mongoexpress:
    image: mongo-express
    container_name: mongo_express_secure_privacy
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:Test123!@mongo:27017
    depends_on:
      - mongo
    restart: always
  users-api:
    build:
      context: .
      dockerfile: Dockerfile.Users
    ports:
      - "5001:5001"
    environment:
      - Encryption__SecretKey=G5hJ/t5pSaTg2QmZ1C0EzBQ6E3cL5bczP2aU3N4VgDk=:6lF1KmIn/DqEdN9aHnC7pg==
      - MongoDb__ConnectionString=mongodb://admin:Test123!@mongo:27017
      - MongoDb__DatabaseName=secure-privacy
      - MongoDb__CollectionName=users
      - ASPNETCORE_URLS=http://*:5001
      - ClientApp=http://localhost:4300
    depends_on:
      - mongo
  products-api:
    build:
      context: .
      dockerfile: Dockerfile.Products
    ports:
      - "5002:5002"
    environment:
      - MongoDb__ConnectionString=mongodb://admin:Test123!@mongo:27017
      - MongoDb__DatabaseName=secure-privacy
      - MongoDb__CategoryCollectionName=categories
      - MongoDb__ProductCollectionName=products
      - ASPNETCORE_URLS=http://*:5002
      - ClientApp=http://localhost:4300
    depends_on:
      - mongo
  gateway:
    image: nginx:alpine
    container_name: nginx_gateway
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9000:9000"
    depends_on:
      - users-api
      - products-api
  client-app:
    build:
      context: .
      dockerfile: Dockerfile.Client
      args:
        USERS_API_URL: "http://localhost:9000/users"
        PRODUCTS_API_URL: "http://localhost:9000/products"
    ports:
      - "4300:80"
    depends_on:
      - gateway
