FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ./src/backend/Products.Api/*.csproj ./src/backend/Products.Api/
RUN dotnet restore ./src/backend/Products.Api/Products.Api.csproj

COPY ./src/backend/Products.Api/ ./src/backend/Products.Api/
WORKDIR /app/src/backend/Products.Api
RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "Products.Api.dll"]
